import { useState } from 'react';
import { useCreateLearningPath } from '../../hooks/useLearningPaths';
import { useUiStore } from '../../store/ui.store';
import type { SkillLevel } from '../../types';
import Modal from '../ui/Modal';
import { Button, InlineLoader } from '../ui/Primitives';
import { errorMessage } from '../../lib/errors';
export default function CreatePathForm() {
 const [name, setName] = useState(''); const [description, setDescription] = useState(''); const [skillLevel, setSkillLevel] = useState<SkillLevel>('beginner');
 const { setCreateModalOpen, setNotification } = useUiStore(); const create = useCreateLearningPath();
 return <Modal title="Create a learning path" description="Give your next learning goal a little structure." onClose={() => setCreateModalOpen(false)} busy={create.isPending}><form className="stack" onSubmit={e => { e.preventDefault(); if (!name.trim()) return; create.mutate({ name: name.trim(), description: description.trim(), skillLevel }, { onSuccess: () => { setNotification({ type: 'success', message: 'Your learning path is ready.' }); setCreateModalOpen(false); } }); }}><div className="form-field"><label htmlFor="path-name">Path name</label><input className="input-field" id="path-name" required maxLength={100} value={name} onChange={e => setName(e.target.value)} placeholder="e.g. Frontend development" /></div><div className="form-field"><label htmlFor="path-description">Description <span className="muted">(optional)</span></label><textarea id="path-description" className="input-field" rows={3} maxLength={500} value={description} onChange={e => setDescription(e.target.value)} placeholder="What would you like to be able to do?" /></div><fieldset className="form-field"><legend>Skill level</legend><div className="level-options">{(['beginner','intermediate','advanced'] as SkillLevel[]).map(level => <button type="button" aria-pressed={skillLevel === level} key={level} onClick={() => setSkillLevel(level)}>{level}</button>)}</div></fieldset>{create.isError && <p className="form-error" role="alert">{errorMessage(create.error)}</p>}<div className="form-actions"><Button variant="secondary" disabled={create.isPending} onClick={() => setCreateModalOpen(false)}>Cancel</Button><Button type="submit" disabled={create.isPending || !name.trim()}>{create.isPending ? <InlineLoader>Creating…</InlineLoader> : 'Create path'}</Button></div></form></Modal>;
}
