import { Check, Flame, ArrowUpRight, Play } from 'lucide-react';
import { Link } from 'react-router-dom';
import type { Chapter, LearningPath } from '../../types';
import { Progress, EmptyState, Badge } from '../ui/Primitives';
import { dateLabel } from '../../lib/format';
export function StreakCard({ streak }: { streak: number }) { return <section className="card"><div className="section-head"><h2>Build your momentum</h2><Flame size={20} style={{ color: 'var(--warning)' }} /></div><p className="streak-count">{streak} <small>day streak</small></p><div className="streak-segments" aria-label={Math.min(streak, 7) + ' of 7 days toward a week-long streak'}>{Array.from({ length: 7 }, (_, i) => <span key={i} className={i < streak ? 'filled' : ''} />)}</div><p className="small muted">{streak >= 7 ? 'A full week of progress. Keep it going.' : 'Small steps add up. Complete a chapter today.'}</p><p className="small muted" style={{ marginTop: 12, fontSize: 10 }}>Streaks follow UTC calendar days.</p></section>; }
export function ProgressOverview({ paths }: { paths: LearningPath[] }) { return <section className="card"><div className="section-head"><h2>Learning progress</h2><Badge>{paths.filter(p => p.progress === 100).length} complete</Badge></div>{paths.length ? paths.slice(0, 5).map(path => <div className="progress-row" key={path._id}><Link to={'/path/' + path._id}>{path.name}</Link><Progress value={path.progress} label={path.name} /><strong>{path.progress}%</strong></div>) : <p className="small muted">Your progress will appear here when you create a path.</p>}</section>; }
export function RecentActivity({ chapters, paths, limit = 4 }: { chapters: Chapter[]; paths: LearningPath[]; limit?: number }) {
 const recent = chapters.filter(c => c.isCompleted && c.completionDate).sort((a, b) => new Date(b.completionDate!).getTime() - new Date(a.completionDate!).getTime()).slice(0, limit);
 return <section className="card"><div className="section-head"><h2>Recent completions</h2><Badge>{recent.length}</Badge></div>{recent.length ? recent.map(chapter => <div key={chapter._id} className="activity-item"><span className="activity-dot"><Check size={13} /></span><div className="grow"><Link className="small font-semibold" to={'/path/' + chapter.learningPathId + '?chapter=' + chapter._id}>{chapter.title}</Link><p className="small muted">{paths.find(p => p._id === chapter.learningPathId)?.name}</p></div><span className="small muted">{dateLabel(chapter.completionDate!)}</span></div>) : <p className="small muted">Complete your first chapter to start your activity story.</p>}</section>;
}
export function ContinueLearning({ paths, chapters }: { paths: LearningPath[]; chapters: Chapter[] }) {
 const path = [...paths].sort((a, b) => new Date(b.updatedAt).getTime() - new Date(a.updatedAt).getTime()).find(p => chapters.some(c => c.learningPathId === p._id && !c.isCompleted));
 const chapter = chapters.find(c => c.learningPathId === path?._id && !c.isCompleted);
 if (!path || !chapter) return <section className="card focus-card"><EmptyState title={paths.length ? 'Ready for your next step?' : 'Make room for something new.'} description={paths.length ? 'Add a chapter to a path or start a new learning goal.' : 'Create a learning path and turn your curiosity into progress.'} action={<Link to="/paths" className="btn-primary">Explore your paths <ArrowUpRight size={16} /></Link>} /></section>;
 return <section className="card focus-card"><div className="row spread"><div className="grow"><div className="eyebrow" style={{ color: 'var(--primary)' }}>Pick up where you left off</div><h2>{chapter.title}</h2><p className="small muted" style={{ marginBottom: 22 }}>{path.name} · {chapter.estimatedMinutes} min estimated</p><div className="row wrap"><Link className="btn-primary" to={'/path/' + path._id + '?chapter=' + chapter._id}><Play size={14} />Continue learning</Link><span className="small muted">{path.progress}% of path complete</span></div></div><div className="focus-art" aria-hidden="true"><Play /></div></div></section>;
}
