import { useState } from 'react';
import { Plus, ChevronDown } from 'lucide-react';
import { useCreateChapter } from '../../hooks/useChapters';
import type { Difficulty } from '../../types';
import { Button } from '../ui/Primitives';
export default function AddChapterForm({ pathId }: { pathId: string }) {
 const [title,setTitle] = useState(''); const [options,setOptions] = useState(false); const [difficulty,setDifficulty] = useState<Difficulty>('medium'); const [minutes,setMinutes] = useState(30); const create = useCreateChapter(pathId);
 return <form className="card stack-sm" style={{ marginTop: 18 }} onSubmit={e => { e.preventDefault(); if (title.trim()) create.mutate({ learningPathId: pathId, title: title.trim(), difficulty, estimatedMinutes: minutes }, { onSuccess: () => { setTitle(''); setOptions(false); } }); }}><label className="small font-semibold" htmlFor="new-chapter">Add your next chapter</label><div className="row"><input className="input-field" id="new-chapter" required maxLength={200} placeholder="What will you learn next?" value={title} onChange={e => setTitle(e.target.value)} /><Button type="submit" disabled={!title.trim() || create.isPending}><Plus size={16} />{create.isPending ? 'Adding…' : 'Add'}</Button></div><button type="button" className="text-link" aria-expanded={options} onClick={() => setOptions(!options)}><ChevronDown size={14} />Difficulty & duration</button>{options && <div className="row wrap"><div className="form-field grow"><label htmlFor="difficulty">Difficulty</label><select id="difficulty" className="input-field" value={difficulty} onChange={e => setDifficulty(e.target.value as Difficulty)}><option value="easy">Easy</option><option value="medium">Medium</option><option value="hard">Hard</option></select></div><div className="form-field grow"><label htmlFor="minutes">Estimated minutes</label><input className="input-field" id="minutes" type="number" min={5} max={300} required value={minutes} onChange={e => setMinutes(Number(e.target.value))} /></div></div>}</form>;
}
