import { useState } from 'react';
import { useChallenge, useGenerateChallenge, useSubmitChallengeResponse } from '../../hooks/useChallenges';
import { SquareTerminal, Lightbulb, Check } from 'lucide-react';
import { Button, Badge, EmptyState, InlineLoader, ErrorState } from '../ui/Primitives';
import { duration } from '../../lib/format';
export default function ChallengePanel({ chapterId }: { chapterId: string }) {
 const query = useChallenge(chapterId); const generate = useGenerateChallenge(chapterId); const submit = useSubmitChallengeResponse(chapterId); const [response,setResponse] = useState(''); const [hint,setHint] = useState(false); const challenge = query.data;
 if (query.isLoading) return <InlineLoader>Loading your challenge…</InlineLoader>;
 if (query.isError) return <ErrorState retry={() => void query.refetch()} />;
 if (!challenge) return <EmptyState icon={<SquareTerminal size={21} />} title="Put your knowledge into practice" description="Generate a practical task for this chapter, then save your written response." action={<Button disabled={generate.isPending} onClick={() => generate.mutate()}>{generate.isPending ? <InlineLoader>Generating…</InlineLoader> : 'Generate challenge'}</Button>} />;
 return <div className="stack"><div className="row spread wrap"><h3>Practice challenge</h3><div className="row"><Badge tone={challenge.isCompleted ? 'success' : 'primary'}>{challenge.isCompleted ? 'Response saved' : challenge.difficulty}</Badge><span className="small muted">{duration(challenge.estimatedMinutes)} estimated</span></div></div><p style={{ whiteSpace: 'pre-wrap' }}>{challenge.task}</p><div className="note"><p className="eyebrow" style={{ marginBottom: 6 }}>Expected outcome</p><p>{challenge.objective}</p></div>{challenge.hint && <div><Button variant="ghost" onClick={() => setHint(!hint)} aria-expanded={hint}><Lightbulb size={16} />{hint ? 'Hide hint' : 'Need a hint?'}</Button>{hint && <p className="small muted">{challenge.hint}</p>}</div>}{challenge.isCompleted ? <><div className="note"><p className="row small" style={{ color: 'var(--success)', marginBottom: 10 }}><Check size={16} />Your saved response</p>{challenge.userResponse}</div><Button variant="secondary" disabled={generate.isPending} onClick={() => { setHint(false); generate.mutate(); }}>{generate.isPending ? 'Generating…' : 'Try a new challenge'}</Button></> : <form className="stack-sm" onSubmit={e => { e.preventDefault(); if (!response.trim()) return; submit.mutate({ challengeId: challenge._id, response: response.trim() }, { onSuccess: () => setResponse('') }); }}><label className="small font-semibold" htmlFor={'response-' + chapterId}>Your response</label><textarea id={'response-' + chapterId} className="input-field" placeholder="Describe your approach, solution, or what you learned…" rows={6} required maxLength={2000} value={response} onChange={e => setResponse(e.target.value)} /><div className="row spread wrap"><span className="small muted">{response.length}/2000 characters</span><Button type="submit" disabled={submit.isPending || !response.trim()}>{submit.isPending ? 'Saving…' : 'Save & complete challenge'}</Button></div></form>}<p className="small muted">Responses are saved as practice work. They are not AI-graded or automatically checked for correctness.</p></div>;
}
