import { ExternalLink, BookOpen, Youtube, RefreshCw } from 'lucide-react';
import type { Resource, ResourceStatus } from '../../types';
import { Button, EmptyState, InlineLoader, Skeleton, ErrorState } from '../ui/Primitives';
export default function ResourceList({ resources, resourceStatus, onDiscover, onRefresh, isDiscovering }: { resources: Resource[]; resourceStatus: ResourceStatus; onDiscover: () => void; onRefresh: () => void; isDiscovering: boolean }) {
 if (resourceStatus === 'pending' || isDiscovering) return <div className="stack-sm"><InlineLoader>Discovering learning resources…</InlineLoader><Skeleton height={65} /><Skeleton height={65} /><p className="small muted">This can take a moment. If a request was interrupted, you can retry.</p><Button variant="secondary" disabled={isDiscovering} onClick={onRefresh}>Retry discovery</Button></div>;
 if (resourceStatus === 'failed') return <ErrorState message="Resources couldn’t be discovered. Please try again." retry={onRefresh} />;
 if (!resources.length) return <EmptyState title="A little guidance goes a long way" description="Discover documentation and videos related to this chapter." action={<Button variant="secondary" onClick={onDiscover}><BookOpen size={16} />Discover resources</Button>} />;
 return <div className="stack-sm"><div className="row spread"><p className="small muted">AI-suggested links · availability is not verified</p><button className="icon-button" aria-label="Refresh resources" onClick={onRefresh}><RefreshCw size={16} /></button></div>{[...resources].sort((a,b) => a.priority - b.priority).map((r,i) => <a key={r.url + i} className="resource-card" href={/^https:\/\//i.test(r.url) ? r.url : undefined} target="_blank" rel="noopener noreferrer"><span className="icon-box">{r.type === 'youtube' ? <Youtube size={19} /> : <BookOpen size={19} />}</span><div className="grow"><span className="eyebrow" style={{ fontSize: 9 }}>{r.type === 'youtube' ? 'Video' : 'Documentation'}</span><h4>{r.title}</h4><p>{r.description}</p></div><ExternalLink size={14} className="muted" /></a>)}</div>;
}
