import { useState } from 'react';
import { Link } from 'react-router-dom';
import { Search, Plus, Sparkles } from 'lucide-react';
import { useLearningPaths } from '../hooks/useLearningPaths';
import { useUiStore } from '../store/ui.store';
import PathCard from '../components/dashboard/PathCard';
import CreatePathForm from '../components/dashboard/CreatePathForm';
import { Button, PageHeading, PageLoading, ErrorState, EmptyState } from '../components/ui/Primitives';
export default function LearningPaths() {
 const query = useLearningPaths(); const ui = useUiStore(); const [search, setSearch] = useState(''); const [status, setStatus] = useState('all'); const [sort, setSort] = useState('updated');
 const paths = (query.data || []).filter(p => (p.name + ' ' + (p.description || '')).toLowerCase().includes(search.toLowerCase()) && (status === 'all' || (status === 'completed' ? p.progress === 100 : status === 'active' ? p.progress > 0 && p.progress < 100 : p.progress === 0))).sort((a,b) => sort === 'name' ? a.name.localeCompare(b.name) : sort === 'progress' ? b.progress - a.progress : new Date(b.updatedAt).getTime() - new Date(a.updatedAt).getTime());
 return <><PageHeading title="Your learning paths" subtitle="Give your goals direction, one chapter at a time." action={<div className="row wrap"><Link className="btn-secondary" to="/ai-roadmap"><Sparkles size={16} />Generate with AI</Link><Button onClick={() => ui.setCreateModalOpen(true)}><Plus size={16} />Create path</Button></div>} />{ui.isCreateModalOpen && <CreatePathForm />}<div className="toolbar"><div className="search-field"><Search size={17} /><input className="input-field" aria-label="Search learning paths" placeholder="Search your learning paths…" value={search} onChange={e => setSearch(e.target.value)} /></div><select className="input-field" aria-label="Filter by status" value={status} onChange={e => setStatus(e.target.value)}><option value="all">All statuses</option><option value="active">In progress</option><option value="new">Not started</option><option value="completed">Completed</option></select><select className="input-field" aria-label="Sort learning paths" value={sort} onChange={e => setSort(e.target.value)}><option value="updated">Recently updated</option><option value="name">Name A–Z</option><option value="progress">Most progress</option></select></div>{query.isLoading ? <PageLoading /> : query.isError ? <ErrorState retry={() => void query.refetch()} /> : paths.length ? <><p className="small muted" style={{ marginBottom: 16 }}>{paths.length} learning path{paths.length === 1 ? '' : 's'}</p><div className="path-grid">{paths.map(p => <PathCard key={p._id} path={p} />)}</div></> : <section className="card"><EmptyState title={query.data?.length ? 'No matching paths' : 'Your next chapter starts here'} description={query.data?.length ? 'Try another search or choose a different status.' : 'Create your first learning path or generate one with AI.'} action={<Button onClick={() => { if (query.data?.length) { setSearch(''); setStatus('all'); } else ui.setCreateModalOpen(true); }}>{query.data?.length ? 'Clear filters' : 'Create your first path'}</Button>} /></section>}</>;
}
